# Math

In [59]:
import math

In [2]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module is always available.  It provides access to the
    mathematical functions defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
        
        This is the smallest integer >= x.
    
    copysign(x, y, /)
        Return a float with the magnitude (absolute value) of

In [3]:
x = 10.5

In [4]:
math.floor(x)

10

In [5]:
math.ceil(x)

11

In [6]:
from math import pi
pi

3.141592653589793

In [12]:
math.log(2,10) #Log 2 base 10

0.30102999566398114

In [19]:
math.degrees(90)

5156.620156177409

# Random

In [36]:
#Random
import random
random.randint(1,10)
random.randrange(1,15)

13

In [53]:
list1 = list(range(50))
random.choice(list1)

18

In [54]:
random.choices(population=list1,k=4)

[43, 3, 30, 13]

In [61]:
# Random Sample

#SAMPLE of data can be done in two ways
#sampling with replacement
#sampling without replacement

[18, 4, 44, 16, 5, 37, 38, 2, 23, 49]

In [63]:
#Sampling without replacement

random.sample(population=list1,k=10)

[15, 26, 22, 24, 49, 39, 0, 25, 5, 6]

In [66]:
random.shuffle(list1)
random.sample(population = list1,k=5)

[47, 36, 8, 33, 14]

# Python Debugger

In [ ]:
#Python Debugger: It is used to track down the error that it may have

In [ ]:
import pdb
pdb.set_trace()
x = [1,2,3]
y = 5
z = 10
sum1 = y+z
sum2 = x+z

--Return--
> <ipython-input-1-10df6f768edb>(2)<module>()->None
-> pdb.set_trace()
(Pdb) x
*** NameError: name 'x' is not defined
(Pdb) y
*** NameError: name 'y' is not defined
(Pdb) z
*** NameError: name 'z' is not defined
(Pdb) x+y
*** NameError: name 'x' is not defined


# Numpy

In [1]:
# Numpy: This is a linear algebra library
import numpy as np

In [10]:
# Numpy arrays
vector: 1D array
Matrix: 2D array

In [8]:
list1 = [1,2,3,4,5]
np.array(list1)

array([1, 2, 3, 4, 5])

In [12]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(5,16,2)

array([ 5,  7,  9, 11, 13, 15])

In [19]:
np.zeros(5) # Float data type

array([0., 0., 0., 0., 0.])

In [23]:
np.ones(5) # Float data type

array([1., 1., 1., 1., 1.])

In [25]:
# Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
# random numbers from 0 to 1
np.random.rand(5)
np.random.rand(5,10)

array([[0.69665209, 0.42250983, 0.23576527, 0.41906299, 0.56100398,
        0.71348984, 0.084665  , 0.02146508, 0.54511516, 0.45609132],
       [0.70455593, 0.02619038, 0.26136311, 0.65449977, 0.03652206,
        0.16305316, 0.01573621, 0.05974946, 0.84673559, 0.85246098],
       [0.57407063, 0.03022263, 0.16973705, 0.69253064, 0.86500215,
        0.15085134, 0.17130482, 0.81646586, 0.27882338, 0.95567519],
       [0.47697516, 0.04446655, 0.34124468, 0.63719   , 0.88782464,
        0.75610055, 0.96193257, 0.46690704, 0.07035438, 0.03233113],
       [0.83266915, 0.98452951, 0.60848937, 0.5632604 , 0.07862322,
        0.23424636, 0.75753036, 0.06822647, 0.57831531, 0.68803826]])

In [36]:
np.random.randint(50)
np.random.randint(50,100)

69

In [44]:
# Braoadcasting
arr = np.arange(20)
arr[1:6] = 500
arr

array([  0, 500, 500, 500, 500, 500,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [50]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
matrix = np.array(matrix)

In [51]:
matrix[0,0]

1

In [52]:
matrix[:,1]

array([2, 5, 8])

In [53]:
matrix[2,2]

9

In [56]:
print(arr)
1/arr

[  0 500 500 500 500 500   6   7   8   9  10  11  12  13  14  15  16  17
  18  19]


C:\Users\hp1\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 0.002     , 0.002     , 0.002     , 0.002     ,
       0.002     , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [55]:
arr + arr

array([   0, 1000, 1000, 1000, 1000, 1000,   12,   14,   16,   18,   20,
         22,   24,   26,   28,   30,   32,   34,   36,   38])

In [57]:
arr.max()

500

In [58]:
arr.min()

0

# Pandas


In [61]:
import pandas as pd

In [69]:
# Series
list1 = [10,2.5,30]
pd.Series(list1)

0    10.0
1     2.5
2    30.0
dtype: float64

In [76]:
# Label
series1 = pd.Series(list1,index = ["W1","W2","W3"])

In [82]:
# You can use index as well as label
print(series1[1])
print(series1["W2"])

2.5
2.5


In [93]:
# DataFrames
# Tables in SQL

np.random.randn(5,4) # Normal distribution

array([[ 0.94130656, -0.38610004, -1.23950758, -0.27132252],
       [-0.03660801, -1.66194624, -0.23853868,  0.7918832 ],
       [ 0.573002  ,  2.07547381, -1.05217892, -0.09113738],
       [-0.28926701,  1.25682716, -0.85116768,  0.77445762],
       [ 1.67074401,  0.90428573, -0.28456934, -0.93909867]])

In [94]:
np.random.rand(5,4)

array([[0.25872483, 0.76782374, 0.43038439, 0.93169293],
       [0.47024726, 0.04557458, 0.88952932, 0.72862382],
       [0.38843164, 0.51702558, 0.80826855, 0.28130533],
       [0.63123655, 0.16465101, 0.03008241, 0.93406632],
       [0.77354985, 0.5966773 , 0.40814154, 0.28745951]])

In [146]:
df = pd.DataFrame(np.random.randn(5,4),index="w1 w2 w3 w4 w5".split(),columns = "A B C D".split())
df

A         B         C         D
w1  0.068387  1.314039  2.602978  1.194250
w2 -0.467941  0.183913 -0.055223 -0.173749
w3 -0.170916  0.351573  0.458006  1.561058
w4  0.023122 -1.003564  1.210580  0.804429
w5 -1.937745 -0.023113  1.289026  1.609601

In [147]:
df[["A","C"]]

A         C
w1  0.068387  2.602978
w2 -0.467941 -0.055223
w3 -0.170916  0.458006
w4  0.023122  1.210580
w5 -1.937745  1.289026

In [148]:
df["A"] 

w1    0.068387
w2   -0.467941
w3   -0.170916
w4    0.023122
w5   -1.937745
Name: A, dtype: float64

In [149]:
# Generate Rows
df.loc["w1"] # Label name: location

A    0.068387
B    1.314039
C    2.602978
D    1.194250
Name: w1, dtype: float64

In [150]:
df.iloc[0] #Index number: index of location

A    0.068387
B    1.314039
C    2.602978
D    1.194250
Name: w1, dtype: float64

In [151]:
df.iloc[2:4]

A         B         C         D
w3 -0.170916  0.351573  0.458006  1.561058
w4  0.023122 -1.003564  1.210580  0.804429

In [152]:
df.loc["w1","A"]

0.06838687425843526

In [153]:
df.iloc[0,0]

0.06838687425843526

In [154]:
df.iloc[:3,2:]

C         D
w1  2.602978  1.194250
w2 -0.055223 -0.173749
w3  0.458006  1.561058

In [155]:
df.iloc[:3,2:]

C         D
w1  2.602978  1.194250
w2 -0.055223 -0.173749
w3  0.458006  1.561058

In [156]:
df.loc[["w1","w2","w3"],["C","D"]]

C         D
w1  2.602978  1.194250
w2 -0.055223 -0.173749
w3  0.458006  1.561058

In [157]:
# DataFrame where values is greater than 0
df>0

A      B      C      D
w1   True   True   True   True
w2  False   True  False  False
w3  False   True   True   True
w4   True  False   True   True
w5  False  False   True   True

In [158]:
# df = df[df>0]
# df

In [159]:
df.reset_index()

index         A         B         C         D
0    w1  0.068387  1.314039  2.602978  1.194250
1    w2 -0.467941  0.183913 -0.055223 -0.173749
2    w3 -0.170916  0.351573  0.458006  1.561058
3    w4  0.023122 -1.003564  1.210580  0.804429
4    w5 -1.937745 -0.023113  1.289026  1.609601

In [162]:
df["E"] = df["C"]+df["D"]
df

A         B         C         D         E
w1  0.068387  1.314039  2.602978  1.194250  3.797229
w2 -0.467941  0.183913 -0.055223 -0.173749 -0.228972
w3 -0.170916  0.351573  0.458006  1.561058  2.019064
w4  0.023122 -1.003564  1.210580  0.804429  2.015009
w5 -1.937745 -0.023113  1.289026  1.609601  2.898627

In [165]:
df["Names"] = "stu1 stu2 stu3 stu4 stu5".split()
df

A         B         C         D         E Names
w1  0.068387  1.314039  2.602978  1.194250  3.797229  stu1
w2 -0.467941  0.183913 -0.055223 -0.173749 -0.228972  stu2
w3 -0.170916  0.351573  0.458006  1.561058  2.019064  stu3
w4  0.023122 -1.003564  1.210580  0.804429  2.015009  stu4
w5 -1.937745 -0.023113  1.289026  1.609601  2.898627  stu5

In [168]:
df=df[["Names","A","B","C","D","E"]]
df

Names         A         B         C         D         E
w1  stu1  0.068387  1.314039  2.602978  1.194250  3.797229
w2  stu2 -0.467941  0.183913 -0.055223 -0.173749 -0.228972
w3  stu3 -0.170916  0.351573  0.458006  1.561058  2.019064
w4  stu4  0.023122 -1.003564  1.210580  0.804429  2.015009
w5  stu5 -1.937745 -0.023113  1.289026  1.609601  2.898627

In [175]:
startup = pd.read_csv("C:\\Users\\hp1\\Desktop\\Wiley python\\50_Startups (1).csv")
startup.head(5)

R&D Spend  Administration  Marketing Spend     Profit  Unnamed: 4  \
0  165349.20       136897.80        471784.10  192261.83         NaN   
1  162597.70       151377.59        443898.53  191792.06         NaN   
2  153441.51       101145.55        407934.54  191050.39         NaN   
3  144372.41       118671.85        383199.62  182901.99         NaN   
4  142107.34        91391.77        366168.42  166187.94         NaN   

   Unnamed: 5  Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  Unnamed: 10  \
0         NaN         NaN         NaN         NaN         NaN          NaN   
1         NaN         NaN         NaN         NaN         NaN          NaN   
2         NaN         NaN         NaN         NaN         NaN          NaN   
3         NaN         NaN         NaN         NaN         NaN          NaN   
4         NaN         NaN         NaN         NaN         NaN          NaN   

  Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16  \
0         NaN         NaN         NaN         NaN         NaN         NaN   
1         NaN         NaN         NaN         NaN         NaN         NaN   
2         NaN         NaN         NaN         NaN         NaN         NaN   
3         NaN         NaN         NaN         NaN         NaN         NaN   
4         NaN         NaN         NaN         NaN         NaN         NaN   

  Unnamed: 17 Unnamed: 18 Unnamed: 19  
0         NaN         NaN         NaN  
1         NaN         NaN         NaN  
2         NaN         NaN         NaN  
3         NaN         NaN         NaN  
4         NaN         NaN         NaN